Url Connection & Data Cleaning

In [41]:
import io
import os
import pandas as pd
import requests
from dotenv import load_dotenv

load_dotenv()
nasa_api = os.getenv("NASA_MAP_KEY")
source = "VIIRS_NOAA20_NRT"
day_range = 3

top_10_locations = {
  "location_1": {
    "name": "Amazon Rainforest",
    "continent": "South America",
    "west_lon": -80.0, 
    "south_lat": -5.0, 
    "east_lon": -50.0, 
    "north_lat": 5.0

  },
  "location_2": {
    "name": "California",
    "continent": "North America",
    "west_lon": -124.5, 
    "south_lat": 32.5, 
    "east_lon": -114.0, 
    "north_lat": 42.0
  },
  "location_3": {
    "name": "Siberian Taiga",
    "continent": "Russia",
    "west_lon": 60.0, 
    "south_lat": 50.0, 
    "east_lon": 140.0, 
    "north_lat": 70.0
  },
  "location_4": {
    "name": "New South Wales",
    "continent": "Austrailia",
    "west_lon": 141.0, 
    "south_lat": -37.5, 
    "east_lon": 154.0, 
    "north_lat": -28.0
  },
  "location_5": {
    "name": "Pantanal",
    "continent": "Brazil",
    "west_lon": -62.0, 
    "south_lat": -22.0, 
    "east_lon": -55.0, 
    "north_lat": -16.0
  },
  "location_6": {
    "name": "Alberta",
    "continent": "Canada",
    "west_lon": -120.0, 
    "south_lat": 49.0, 
    "east_lon": -110.0, 
    "north_lat": 60.0
  },
  "location_7": {
    "name": "Mediterranean Basin",
    "continent": "Southern Europe",
    "west_lon": -10.0, 
    "south_lat": 30.0, 
    "east_lon": 40.0, 
    "north_lat": 46.0
  },
  "location_8": {
    "name": "Indonesia",
    "continent": "Southeast Asia",
    "west_lon": 95.0, 
    "south_lat": -11.0, 
    "east_lon": 141.0, 
    "north_lat": 6.0
  },
  "location_9": {
    "name": "Greece",
    "continent": "Southern Europe",
    "west_lon": 19.0, 
    "south_lat": 34.0, 
    "east_lon": 28.0, 
    "north_lat": 42.0
  },
  "location_10": {
    "name": "Algeria",
    "continent": "North Africa",
    "west_lon": -9.0, 
    "south_lat": 19.0, 
    "east_lon": 12.0, 
    "north_lat": 37.0
  }
}

target_key = "location_6"

location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))

column_duplicates = df.columns.is_unique # No Duplicates
index_duplicates = df.index.is_unique # No Duplicates

null_values = df.isnull().values.any() # No missing data fields

Unique Data & Data Exploration

Location #1: Amazon Rainforest

In [45]:
target_key = "location_1"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,2.96398,-75.17831,306.69,0.39,0.36,2026-05-25,625,N20,VIIRS,n,2.0NRT,291.01,0.72,N
1,3.28766,-75.37979,309.67,0.40,0.37,2026-05-25,625,N20,VIIRS,n,2.0NRT,280.91,1.20,N
2,3.97210,-72.24199,307.29,0.41,0.37,2026-05-25,625,N20,VIIRS,n,2.0NRT,288.59,0.50,N
3,3.97550,-72.24146,311.58,0.41,0.37,2026-05-25,625,N20,VIIRS,n,2.0NRT,288.97,1.32,N
4,4.49954,-74.14190,308.05,0.38,0.36,2026-05-25,625,N20,VIIRS,n,2.0NRT,282.24,1.04,N

Location #2: California

In [46]:
target_key = "location_2"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,33.79247,-117.47572,298.96,0.38,0.36,2026-05-25,939,N20,VIIRS,n,2.0NRT,284.46,0.45,N
1,33.79575,-117.47498,296.42,0.38,0.36,2026-05-25,939,N20,VIIRS,n,2.0NRT,285.23,0.45,N
2,34.03622,-118.10632,306.57,0.39,0.36,2026-05-25,939,N20,VIIRS,n,2.0NRT,285.63,0.42,N
3,34.03757,-117.89278,309.19,0.39,0.36,2026-05-25,939,N20,VIIRS,n,2.0NRT,282.59,0.26,N
4,34.11372,-117.92329,298.31,0.39,0.36,2026-05-25,939,N20,VIIRS,n,2.0NRT,286.16,0.36,N

Location #3: Siberian Taiga

In [47]:
target_key = "location_3"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,51.09161,137.06508,327.90,0.43,0.62,2026-05-25,230,N20,VIIRS,n,2.0NRT,290.87,5.29,D
1,51.32813,134.84013,326.43,0.51,0.66,2026-05-25,230,N20,VIIRS,n,2.0NRT,291.54,3.26,D
2,51.47235,134.98787,332.38,0.50,0.65,2026-05-25,230,N20,VIIRS,n,2.0NRT,292.59,4.69,D
3,51.47325,134.98077,350.02,0.50,0.65,2026-05-25,230,N20,VIIRS,n,2.0NRT,292.84,6.85,D
4,51.47435,134.97356,335.55,0.50,0.66,2026-05-25,230,N20,VIIRS,n,2.0NRT,292.27,9.37,D

Location #4: New South Wales

In [48]:
target_key = "location_4"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,-36.95286,145.48997,337.70,0.42,0.45,2026-05-25,347,N20,VIIRS,n,2.0NRT,281.58,4.83,D
1,-36.95272,145.48894,338.02,0.42,0.45,2026-05-25,347,N20,VIIRS,n,2.0NRT,282.12,5.94,D
2,-36.38032,145.13565,338.61,0.43,0.46,2026-05-25,347,N20,VIIRS,n,2.0NRT,291.46,9.89,D
3,-35.99106,145.55495,335.74,0.41,0.45,2026-05-25,347,N20,VIIRS,n,2.0NRT,284.33,5.13,D
4,-35.99062,145.55952,326.33,0.41,0.45,2026-05-25,347,N20,VIIRS,n,2.0NRT,281.98,4.43,D

Location #5: Pantanal

In [49]:
target_key = "location_5"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,-20.06565,-55.75681,303.49,0.40,0.37,2026-05-25,453,N20,VIIRS,n,2.0NRT,289.85,0.58,N
1,-17.48135,-59.48372,302.09,0.43,0.46,2026-05-25,453,N20,VIIRS,n,2.0NRT,289.22,0.97,N
2,-17.47717,-59.48285,305.88,0.43,0.46,2026-05-25,453,N20,VIIRS,n,2.0NRT,289.11,0.97,N
3,-17.47640,-59.48690,305.39,0.43,0.46,2026-05-25,453,N20,VIIRS,n,2.0NRT,288.91,2.34,N
4,-17.47486,-59.49504,297.64,0.43,0.46,2026-05-25,453,N20,VIIRS,n,2.0NRT,287.23,1.13,N

Location #6: Alberta

In [50]:
target_key = "location_6"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,49.06583,-115.52300,312.34,0.43,0.38,2026-05-25,934,N20,VIIRS,n,2.0NRT,280.26,1.31,N
1,50.17904,-114.86153,305.45,0.42,0.38,2026-05-25,934,N20,VIIRS,n,2.0NRT,278.84,2.08,N
2,56.96443,-111.46832,298.38,0.41,0.37,2026-05-25,934,N20,VIIRS,n,2.0NRT,277.61,0.40,N
3,57.00422,-111.47922,302.98,0.41,0.37,2026-05-25,934,N20,VIIRS,n,2.0NRT,283.77,1.23,N
4,57.00759,-111.47781,328.26,0.41,0.37,2026-05-25,934,N20,VIIRS,n,2.0NRT,283.36,3.49,N

Location #7: Mediterranean Basin

In [51]:
target_key = "location_7"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,39.86584,26.24398,306.16,0.50,0.66,2026-05-25,109,N20,VIIRS,n,2.0NRT,284.67,1.17,N
1,40.28621,23.44395,299.98,0.35,0.57,2026-05-25,109,N20,VIIRS,n,2.0NRT,284.70,0.58,N
2,41.50270,19.74380,307.71,0.43,0.46,2026-05-25,109,N20,VIIRS,n,2.0NRT,287.81,1.05,N
3,41.54755,19.72273,296.94,0.43,0.46,2026-05-25,109,N20,VIIRS,n,2.0NRT,286.89,0.60,N
4,42.57131,12.67485,311.17,0.38,0.36,2026-05-25,109,N20,VIIRS,n,2.0NRT,288.60,0.67,N

Location #8: Indonesia

In [52]:
target_key = "location_8"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,-3.74699,138.71848,344.01,0.41,0.45,2026-05-25,353,N20,VIIRS,n,2.0NRT,292.12,5.59,D
1,-3.74653,138.71805,344.52,0.41,0.45,2026-05-25,353,N20,VIIRS,n,2.0NRT,292.20,6.06,D
2,-3.71190,138.44420,352.65,0.43,0.46,2026-05-25,353,N20,VIIRS,n,2.0NRT,299.94,49.29,D
3,-3.69272,138.71796,340.57,0.41,0.45,2026-05-25,353,N20,VIIRS,n,2.0NRT,292.41,22.98,D
4,-3.67679,139.07365,339.18,0.39,0.44,2026-05-25,353,N20,VIIRS,n,2.0NRT,292.04,3.04,D

Location #9: Greece

In [53]:
target_key = "location_9"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,39.86584,26.24398,306.16,0.50,0.66,2026-05-25,109,N20,VIIRS,n,2.0NRT,284.67,1.17,N
1,40.28621,23.44395,299.98,0.35,0.57,2026-05-25,109,N20,VIIRS,n,2.0NRT,284.70,0.58,N
2,41.50270,19.74380,307.71,0.43,0.46,2026-05-25,109,N20,VIIRS,n,2.0NRT,287.81,1.05,N
3,41.54755,19.72273,296.94,0.43,0.46,2026-05-25,109,N20,VIIRS,n,2.0NRT,286.89,0.60,N
4,38.42731,27.21595,301.79,0.62,0.71,2026-05-25,111,N20,VIIRS,n,2.0NRT,285.52,0.82,N

Location #10: Algeria

In [54]:
target_key = "location_6"
location_data = top_10_locations[target_key]
west_lon = location_data["west_lon"]
south_lat = location_data["south_lat"]
east_lon = location_data["east_lon"]
north_lat = location_data["north_lat"]

data_base_url = "https://firms.modaps.eosdis.nasa.gov/api/area"
prediction_url = f"{data_base_url}/csv/{nasa_api}/{source}/{west_lon},{south_lat},{east_lon},{north_lat}/{day_range}"

response = requests.get(prediction_url)
response.raise_for_status() 

df = pd.read_csv(io.StringIO(response.text))
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,49.06583,-115.52300,312.34,0.43,0.38,2026-05-25,934,N20,VIIRS,n,2.0NRT,280.26,1.31,N
1,50.17904,-114.86153,305.45,0.42,0.38,2026-05-25,934,N20,VIIRS,n,2.0NRT,278.84,2.08,N
2,56.96443,-111.46832,298.38,0.41,0.37,2026-05-25,934,N20,VIIRS,n,2.0NRT,277.61,0.40,N
3,57.00422,-111.47922,302.98,0.41,0.37,2026-05-25,934,N20,VIIRS,n,2.0NRT,283.77,1.23,N
4,57.00759,-111.47781,328.26,0.41,0.37,2026-05-25,934,N20,VIIRS,n,2.0NRT,283.36,3.49,N